
project_id = "ahaupfnvqfhchptxbddl"

[api]
enabled = true
port = 54321
# Remove the invalid 'types' key

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

# Renamed from 'edge_functions' to 'functions' which is the correct key
[functions]
enabled = true
