
project_id = "ahaupfnvqfhchptxbddl"

[api]
enabled = true
port = 54321
types = "../../types.ts"

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

[edge_functions]
enabled = true
