// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukedswaxpldombgjilvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZWRzd2F4cGxkb21iZ2ppbHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNjk5OTksImV4cCI6MjA1Njg0NTk5OX0.J1S8icZKmQwYQkcVOFYqTJSP7x0n0mGV-GIdJJVZwXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);