// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahaupfnvqfhchptxbddl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoYXVwZm52cWZoY2hwdHhiZGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMDA1MTAsImV4cCI6MjA1NTg3NjUxMH0.AL6myc7fUP3HcoBONAtf4flfWxkBd70eSTH8yQmajd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);